version: '3.8'
name: notdefteri

services:
  notes_web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: notdefteri_web
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ${CASA_APP_DATA}/static:/app/staticfiles
      - ${CASA_APP_DATA}/media:/app/media
      - ${CASA_APP_DATA}/db:/app/db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - SECRET_KEY=degistirin-buraya-guvenli-bir-anahtar-yazin
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,192.168.1.121

volumes:
  notes_data: 