version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - notes_static:/app/staticfiles
      - notes_media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ../.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - notes_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notesdb
      - POSTGRES_USER=notesuser
      - POSTGRES_PASSWORD=notespass

volumes:
  notes_postgres_data:
  notes_static:
  notes_media: 